#80
Hackathon5-TeamD/evolution-quest pull request #82
Opened 2022-06-06 18:43 UTC by Rinasham

fix #80

フォントをFigmaのデザインのものに一旦変更しておきました。

こっちのフォントの方がいいぜ！みたいなのあったら言ってください（*’∀’人）

2022-06-06 19:58 UTC, kobakichi commented
今
`git fetch origin pull/82/head:PR-82`
にて動作確認しましたが、エラーが発生しています。
<img width="1601" alt="スクリーンショット 2022-06-07 4 54 34" src="https://user-images.githubusercontent.com/85420909/172238059-a4f2a452-98e9-4dc2-9816-2f0edfb554a7.png">


私の環境のせいなのかも知れないので、どなたか検証をお願いいたします。

2022-06-06 20:00 UTC, Rinasham commented
モジュールがインストールされていないエラーかと思うので、一度dockerコンテナを潰して立て直してみてください(`·⊝·´)

2022-06-06 21:13 UTC, kobakichi commented
sidebar.tsxのloginのリンクですが、URL　/loginではなく、現状/でloginページへ遷移してます！！！

他は動作問題なさそうですね。
他の方にも検証をお願いしたいです。

2022-06-07 10:53 UTC, Terralien-jp requested changes
* userpageページへのフォント反映を確認しました
* resultページのフォント反映を確認しました
* mainページへのフォント反映を確認しました

※サイドバーのLogin先が/になっているのは変更予告ありました！

修正依頼：前２つと同じでサイドメニューのuserリンクをuserpageへ

2022-06-07 11:24 UTC, Terralien-jp commented
pullするリモートブランチは
feature/#80
です。#82はこのプルリクの番号ですね！

2022-06-07 11:24 UTC, merged

2022-06-07 11:25 UTC, Rinasham commented
@Terralien-jp 
間違いましたすみませーん！！